server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**,/api/v1/available_dates/**,/api/v1/reviews/**

        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/api/v1/authentication/**,/api/v1/roles/**,/api/v1/users/**

        - id: management-service
          uri: lb://management-service
          predicates:
            - Path=/api/v1/animals/**,/api/v1/enclosures/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/posts/**

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/advisors/**,/api/v1/farmers/**,/api/v1/notifications/**,/api/v1/profiles/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5

  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5