server:
  port: 8080
  error:
    include-message: always

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**
            - Path=/api/v1/available_dates/**
            - Path=/api/v1/reviews/**
        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/api/v1/authentication/**
            - Path=/api/v1/roles/**
            - Path=/api/v1/users/**
            - Path=/iam/swagger-ui/**
            - Path=/iam/v3/api-docs
            - Path=/iam/swagger-resources/**
            - Path=/iam/webjars/**
            - Path=/iam/swagger-ui.html
          filters:
            - StripPrefix=1
        - id: management-service
          uri: lb://management-service
          predicates:
            - Path=/api/v1/animals/**
            - Path=/api/v1/enclosures/**
            - Path=/management/swagger-ui/**
            - Path=/management/v3/api-docs
            - Path=/management/swagger-resources/**
            - Path=/management/webjars/**
            - Path=/management/swagger-ui.html
          filters:
            - StripPrefix=1
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/posts/**
            - Path=/post/swagger-ui/**
            - Path=/post/v3/api-docs
            - Path=/post/swagger-resources/**
            - Path=/post/webjars/**
            - Path=/post/swagger-ui.html
          filters:
            - StripPrefix=1
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/advisors/**
            - Path=/api/v1/farmers/**
            - Path=/api/v1/notifications/**
            - Path=/api/v1/profiles/**
            - Path=/profile/swagger-ui/**
            - Path=/profile/v3/api-docs
            - Path=/profile/swagger-resources/**
            - Path=/profile/webjars/**
            - Path=/profile/swagger-ui.html
          filters:
            - StripPrefix=1

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5

  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5